package com.ahajri.v2m.domain;

// Generated 16 nov. 2014 02:11:02 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

import org.codehaus.jackson.map.annotate.JsonDeserialize;
import org.codehaus.jackson.map.annotate.JsonSerialize;

import com.ahajri.v2m.domain.json.serialization.MessageDeserializer;
import com.ahajri.v2m.domain.json.serialization.MessageSerializer;

/**
 * Message generated by hbm2java
 */
@Entity
@Table(name = "message", schema = "public")
@SequenceGenerator(name="msgidseq",sequenceName="msg_id_seq")
//@JsonDeserialize(using = MessageDeserializer.class)
//@JsonSerialize(using = MessageSerializer.class)
public class Message implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 2322204768701676476L;
	private long id;
	private VoiceFile voiceFile;
	private Sender sender;
	private Receiver receiver;
	private String subject;
	private String body;

	public Message() {
	}

	public Message(long id, VoiceFile voiceFile, Sender sender, Receiver receiver) {
		this.id = id;
		this.voiceFile = voiceFile;
		this.sender = sender;
		this.receiver = receiver;
	}

	public Message(long id, VoiceFile voiceFile, Sender sender, Receiver receiver, String subject, String body) {
		this.id = id;
		this.voiceFile = voiceFile;
		this.sender = sender;
		this.receiver = receiver;
		this.subject = subject;
		this.body = body;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	@GeneratedValue(generator = "msgidseq")
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "ref_voice_file", nullable = false)
	public VoiceFile getVoiceFile() {
		return this.voiceFile;
	}

	public void setVoiceFile(VoiceFile voiceFile) {
		this.voiceFile = voiceFile;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "ref_sender", nullable = false)
	public Sender getSender() {
		return this.sender;
	}

	public void setSender(Sender sender) {
		this.sender = sender;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "ref_receiver", nullable = false)
	public Receiver getReceiver() {
		return this.receiver;
	}

	public void setReceiver(Receiver receiver) {
		this.receiver = receiver;
	}

	@Column(name = "subject", length = 150)
	public String getSubject() {
		return this.subject;
	}

	public void setSubject(String subject) {
		this.subject = subject;
	}

	@Column(name = "body", length = 450)
	public String getBody() {
		return this.body;
	}

	public void setBody(String body) {
		this.body = body;
	}

	@Override
	public String toString() {
		return "Message [id=" + id + ", sender=" + sender.toString() + ", receiver="
				+ receiver.toString() + "]";
	}

	
}
