package com.ahajri.v2m.domain;

// Generated 16 nov. 2014 02:11:02 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

import org.codehaus.jackson.map.annotate.JsonDeserialize;
import org.codehaus.jackson.map.annotate.JsonSerialize;

import com.ahajri.v2m.domain.json.serialization.PersonDeserializer;
import com.ahajri.v2m.domain.json.serialization.PersonSerializer;

/**
 * Person generated by hbm2java
 */
@Entity
@Table(name = "person", schema = "public", uniqueConstraints = @UniqueConstraint(columnNames = "email"))
@SequenceGenerator(name="personidseq",sequenceName="person_id_seq")
@JsonDeserialize(using = PersonDeserializer.class)
@JsonSerialize(using = PersonSerializer.class)
public class Person implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 7812536213460687551L;
	private long id;
	private String fullName;
	private String email;
	private Set<Sender> senders = new HashSet<Sender>(0);
	private Set<Receiver> receivers = new HashSet<Receiver>(0);

	public Person() {
	}

	public Person(long id, String fullName, String email) {
		this.id = id;
		this.fullName = fullName;
		this.email = email;
	}

	public Person(long id, String fullName, String email, Set<Sender> senders, Set<Receiver> receivers) {
		this.id = id;
		this.fullName = fullName;
		this.email = email;
		this.senders = senders;
		this.receivers = receivers;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	@GeneratedValue(generator="personidseq")
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "full_name", nullable = false, length = 250)
	public String getFullName() {
		return this.fullName;
	}

	public void setFullName(String fullName) {
		this.fullName = fullName;
	}

	@Column(name = "email", unique = true, nullable = false, length = 150)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "person")
	public Set<Sender> getSenders() {
		return this.senders;
	}

	public void setSenders(Set<Sender> senders) {
		this.senders = senders;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "person")
	public Set<Receiver> getReceivers() {
		return this.receivers;
	}

	public void setReceivers(Set<Receiver> receivers) {
		this.receivers = receivers;
	}

	@Override
	public String toString() {
		return "Person [id=" + id + ", fullName=" + fullName + ", email="
				+ email + "]";
	}
	
	

}
