package com.ahajri.v2m.domain;

// Generated 16 nov. 2014 02:11:02 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

import org.codehaus.jackson.map.annotate.JsonDeserialize;
import org.codehaus.jackson.map.annotate.JsonSerialize;

import com.ahajri.v2m.domain.json.serialization.SenderDeserializer;
import com.ahajri.v2m.domain.json.serialization.SenderSerializer;

/**
 * Sender generated by hbm2java
 */
@Entity
@Table(name = "sender", schema = "public")
@SequenceGenerator(name="senderidseq",sequenceName="sender_id_seq")
@JsonDeserialize(using = SenderDeserializer.class)
@JsonSerialize(using = SenderSerializer.class)
public class Sender implements java.io.Serializable {

	/**
	 * Serial Version UID
	 */
	private static final long serialVersionUID = -7431533778929543728L;
	private long id;
	private Person person;
	private Set<Message> messages = new HashSet<Message>(0);

	public Sender() {
	}

	public Sender(long id) {
		this.id = id;
	}

	public Sender(long id, Person person, Set<Message> messages) {
		this.id = id;
		this.person = person;
		this.messages = messages;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	@GeneratedValue(generator="senderidseq")
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "ref_person")
	public Person getPerson() {
		return this.person;
	}

	public void setPerson(Person person) {
		this.person = person;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "sender")
	public Set<Message> getMessages() {
		return this.messages;
	}

	public void setMessages(Set<Message> messages) {
		this.messages = messages;
	}

	@Override
	public String toString() {
		return "Sender [id=" + id + ", person=" + person.toString() + "]";
	}

}
