package com.ahajri.v2m.domain;

// Generated 16 nov. 2014 02:11:02 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

import org.codehaus.jackson.map.annotate.JsonDeserialize;
import org.codehaus.jackson.map.annotate.JsonSerialize;

import com.ahajri.v2m.domain.json.serialization.VoiceFileDeserializer;
import com.ahajri.v2m.domain.json.serialization.VoiceFileSerializer;

/**
 * VoiceFile generated by hbm2java
 */
@Entity
@Table(name = "voice_file", schema = "public")
@SequenceGenerator(name="vfileidseq",sequenceName="voice_file_id_seq")
@JsonDeserialize(using = VoiceFileDeserializer.class)
@JsonSerialize(using = VoiceFileSerializer.class)
public class VoiceFile implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 5635226252318265352L;
	private long id;
	private String path;
	private String format;
	private Set<Message> messages = new HashSet<Message>(0);

	public VoiceFile() {
	}

	public VoiceFile(long id, String path) {
		this.id = id;
		this.path = path;
	}

	public VoiceFile(long id, String path, String format, Set<Message> messages) {
		this.id = id;
		this.path = path;
		this.format = format;
		this.messages = messages;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	@GeneratedValue(generator="vfileidseq")
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "path", nullable = false, length = 150)
	public String getPath() {
		return this.path;
	}

	public void setPath(String path) {
		this.path = path;
	}

	@Column(name = "format", length = 10)
	public String getFormat() {
		return this.format;
	}

	public void setFormat(String format) {
		this.format = format;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "voiceFile")
	public Set<Message> getMessages() {
		return this.messages;
	}

	public void setMessages(Set<Message> messages) {
		this.messages = messages;
	}

	@Override
	public String toString() {
		return "VoiceFile [id=" + id + ", path=" + path + ", format=" + format
				+ "]";
	}

}
