CREATE TABLE country (
 ID INTEGER NOT NULL,
 country_code VARCHAR(10) NOT NULL ,
 country_name VARCHAR(4000) NOT NULL ,
 CURRENCY VARCHAR(4),
 CONSTRAINT "country_PK" PRIMARY KEY (ID) ,
 CONSTRAINT "country_code_UNIQUE" UNIQUE (country_code) 
);

-- INSERTING into country
Insert into country (ID,country_code,country_name,CURRENCY) values (1,'ac','Ascension Island',null);
Insert into country (ID,country_code,country_name,CURRENCY) values (2,'ad','Andorra',null);
Insert into country (ID,country_code,country_name,CURRENCY) values (3,'ae','United Arab Emirates',null);
Insert into country (ID,country_code,country_name,CURRENCY) values (4,'af','Afghanistan',null);
Insert into country (ID,country_code,country_name,CURRENCY) values (5,'ag','Antigua and Barbuda',null);
Insert into country (ID,country_code,country_name,CURRENCY) values (6,'ai','Anguilla',null);
Insert into country (ID,country_code,country_name,CURRENCY) values (7,'al','Albania',null);
Insert into country (ID,country_code,country_name,CURRENCY) values (8,'am','Armenia',null);
Insert into country (ID,country_code,country_name,CURRENCY) values (9,'an','Netherlands Antilles',null);
Insert into country (ID,country_code,country_name,CURRENCY) values (10,'ao','Angola',null);
Insert into country (ID,country_code,country_name,CURRENCY) values (11,'aq','Antartica',null);
Insert into country (ID,country_code,country_name,CURRENCY) values (12,'ar','Argentina',null);
Insert into country (ID,country_code,country_name,CURRENCY) values (13,'as','American Samoa',null);
Insert into country (ID,country_code,country_name,CURRENCY) values (14,'au','Australia',null);
Insert into country (ID,country_code,country_name,CURRENCY) values (15,'aw','Aruba',null);
Insert into country (ID,country_code,country_name,CURRENCY) values (16,'az','Azerbaijan',null);
Insert into country (ID,country_code,country_name,CURRENCY) values (17,'ba','Bosnia and Herzegovina',null);
Insert into country (ID,country_code,country_name,CURRENCY) values (18,'bb','Barbados',null);
Insert into country (ID,country_code,country_name,CURRENCY) values (19,'bd','Bangladesh',null);
Insert into country (ID,country_code,country_name,CURRENCY) values (20,'be','Belgium',null);
Insert into country (ID,country_code,country_name,CURRENCY) values (21,'bf','Burkina Faso',null);
Insert into country (ID,country_code,country_name,CURRENCY) values (22,'bg','Bulgaria',null);
Insert into country (ID,country_code,country_name,CURRENCY) values (23,'bh','Bahrain',null);
Insert into country (ID,country_code,country_name,CURRENCY) values (24,'bi','Burundi',null);
Insert into country (ID,country_code,country_name,CURRENCY) values (25,'bj','Benin',null);
Insert into country (ID,country_code,country_name,CURRENCY) values (26,'bm','Bermuda',null);
Insert into country (ID,country_code,country_name,CURRENCY) values (27,'bn','Brunei Darussalam',null);
Insert into country (ID,country_code,country_name,CURRENCY) values (28,'bo','Bolivia',null);
Insert into country (ID,country_code,country_name,CURRENCY) values (29,'br','Brazil',null);
Insert into country (ID,country_code,country_name,CURRENCY) values (30,'bs','Bahamas',null);
Insert into country (ID,country_code,country_name,CURRENCY) values (31,'bt','Bhutan',null);
Insert into country (ID,country_code,country_name,CURRENCY) values (32,'bv','Bouvet Island',null);
Insert into country (ID,country_code,country_name,CURRENCY) values (33,'bw','Botswana',null);
Insert into country (ID,country_code,country_name,CURRENCY) values (34,'by','Belarus',null);
Insert into country (ID,country_code,country_name,CURRENCY) values (35,'bz','Belize',null);
Insert into country (ID,country_code,country_name,CURRENCY) values (36,'ca','Canada',null);
Insert into country (ID,country_code,country_name,CURRENCY) values (37,'cc','Cocos (Keeling) Islands',null);
Insert into country (ID,country_code,country_name,CURRENCY) values (38,'cd','Congo, Democratic People''s Republic',null);
Insert into country (ID,country_code,country_name,CURRENCY) values (39,'cf','Central African Republic',null);
Insert into country (ID,country_code,country_name,CURRENCY) values (40,'cg','Congo, Republic of',null);
Insert into country (ID,country_code,country_name,CURRENCY) values (41,'ch','Switzerland',null);
Insert into country (ID,country_code,country_name,CURRENCY) values (42,'ci','Cote d''Ivoire',null);
Insert into country (ID,country_code,country_name,CURRENCY) values (43,'ck','Cook Islands',null);
Insert into country (ID,country_code,country_name,CURRENCY) values (44,'cl','Chile',null);
Insert into country (ID,country_code,country_name,CURRENCY) values (45,'cm','Cameroon',null);
Insert into country (ID,country_code,country_name,CURRENCY) values (46,'cn','China',null);
Insert into country (ID,country_code,country_name,CURRENCY) values (47,'co','Colombia',null);
Insert into country (ID,country_code,country_name,CURRENCY) values (48,'cr','Costa Rica',null);
Insert into country (ID,country_code,country_name,CURRENCY) values (49,'cu','Cuba',null);
Insert into country (ID,country_code,country_name,CURRENCY) values (50,'cv','Cap Verde',null);
Insert into country (ID,country_code,country_name,CURRENCY) values (51,'cx','Christmas Island',null);
Insert into country (ID,country_code,country_name,CURRENCY) values (52,'cy','Cyprus',null);
Insert into country (ID,country_code,country_name,CURRENCY) values (53,'cz','Czeck Republic',null);
Insert into country (ID,country_code,country_name,CURRENCY) values (54,'de','Germany',null);
Insert into country (ID,country_code,country_name,CURRENCY) values (55,'dj','Djibouti',null);
Insert into country (ID,country_code,country_name,CURRENCY) values (56,'dk','Denmark',null);
Insert into country (ID,country_code,country_name,CURRENCY) values (57,'dm','Dominica',null);
Insert into country (ID,country_code,country_name,CURRENCY) values (58,'do','Dominican Republic',null);
Insert into country (ID,country_code,country_name,CURRENCY) values (59,'dz','Algeria',null);
Insert into country (ID,country_code,country_name,CURRENCY) values (60,'ec','Ecuador',null);
Insert into country (ID,country_code,country_name,CURRENCY) values (61,'ee','Estonia',null);
Insert into country (ID,country_code,country_name,CURRENCY) values (62,'eg','Egypt',null);
Insert into country (ID,country_code,country_name,CURRENCY) values (63,'eh','Western Sahara',null);
Insert into country (ID,country_code,country_name,CURRENCY) values (64,'er','Eritrea',null);
Insert into country (ID,country_code,country_name,CURRENCY) values (65,'es','Spain',null);
Insert into country (ID,country_code,country_name,CURRENCY) values (66,'et','Ethiopia',null);
Insert into country (ID,country_code,country_name,CURRENCY) values (67,'fi','Finland',null);
Insert into country (ID,country_code,country_name,CURRENCY) values (68,'fj','Fiji',null);
Insert into country (ID,country_code,country_name,CURRENCY) values (69,'fk','Falkland Islands (Malvina)',null);
Insert into country (ID,country_code,country_name,CURRENCY) values (70,'fm','Micronesia, Federal State of',null);
Insert into country (ID,country_code,country_name,CURRENCY) values (71,'fo','Faroe Islands',null);
Insert into country (ID,country_code,country_name,CURRENCY) values (72,'fr','France',null);
Insert into country (ID,country_code,country_name,CURRENCY) values (73,'ga','Gabon',null);
Insert into country (ID,country_code,country_name,CURRENCY) values (74,'gd','Grenada',null);
Insert into country (ID,country_code,country_name,CURRENCY) values (75,'ge','Georgia',null);
Insert into country (ID,country_code,country_name,CURRENCY) values (76,'gf','French Guiana',null);
Insert into country (ID,country_code,country_name,CURRENCY) values (77,'gg','Guernsey',null);
Insert into country (ID,country_code,country_name,CURRENCY) values (78,'gh','Ghana',null);
Insert into country (ID,country_code,country_name,CURRENCY) values (79,'gi','Gibraltar',null);
Insert into country (ID,country_code,country_name,CURRENCY) values (80,'gl','Greenland',null);
Insert into country (ID,country_code,country_name,CURRENCY) values (81,'gm','Gambia',null);
Insert into country (ID,country_code,country_name,CURRENCY) values (82,'gn','Guinea',null);
Insert into country (ID,country_code,country_name,CURRENCY) values (83,'gp','Guadeloupe',null);
Insert into country (ID,country_code,country_name,CURRENCY) values (84,'gq','Equatorial Guinea',null);
Insert into country (ID,country_code,country_name,CURRENCY) values (85,'gr','Greece',null);
Insert into country (ID,country_code,country_name,CURRENCY) values (86,'gs','South Georgia and the South Sandwich Islands',null);
Insert into country (ID,country_code,country_name,CURRENCY) values (87,'gt','Guatemala',null);
Insert into country (ID,country_code,country_name,CURRENCY) values (88,'gu','Guam',null);
Insert into country (ID,country_code,country_name,CURRENCY) values (89,'gw','Guinea-Bissau',null);
Insert into country (ID,country_code,country_name,CURRENCY) values (90,'gy','Guyana',null);
Insert into country (ID,country_code,country_name,CURRENCY) values (91,'hk','Hong Kong',null);
Insert into country (ID,country_code,country_name,CURRENCY) values (92,'hm','Heard and McDonald Islands',null);
Insert into country (ID,country_code,country_name,CURRENCY) values (93,'hn','Honduras',null);
Insert into country (ID,country_code,country_name,CURRENCY) values (94,'hr','Croatia/Hrvatska',null);
Insert into country (ID,country_code,country_name,CURRENCY) values (95,'ht','Haiti',null);
Insert into country (ID,country_code,country_name,CURRENCY) values (96,'hu','Hungary',null);
Insert into country (ID,country_code,country_name,CURRENCY) values (97,'id','Indonesia',null);
Insert into country (ID,country_code,country_name,CURRENCY) values (98,'ie','Ireland',null);
Insert into country (ID,country_code,country_name,CURRENCY) values (99,'il','Israel',null);
Insert into country (ID,country_code,country_name,CURRENCY) values (100,'im','Isle of Man',null);
Insert into country (ID,country_code,country_name,CURRENCY) values (101,'in','India',null);
Insert into country (ID,country_code,country_name,CURRENCY) values (102,'io','British Indian Ocean Territory',null);
Insert into country (ID,country_code,country_name,CURRENCY) values (103,'iq','Iraq',null);
Insert into country (ID,country_code,country_name,CURRENCY) values (104,'ir','Iran (Islamic Republic of)',null);
Insert into country (ID,country_code,country_name,CURRENCY) values (105,'is','Iceland',null);
Insert into country (ID,country_code,country_name,CURRENCY) values (106,'it','Italy',null);
Insert into country (ID,country_code,country_name,CURRENCY) values (107,'je','Jersey',null);
Insert into country (ID,country_code,country_name,CURRENCY) values (108,'jm','Jamaica',null);
Insert into country (ID,country_code,country_name,CURRENCY) values (109,'jo','Jordan',null);
Insert into country (ID,country_code,country_name,CURRENCY) values (110,'jp','Japan','Yen');
Insert into country (ID,country_code,country_name,CURRENCY) values (111,'ke','Kenya',null);
Insert into country (ID,country_code,country_name,CURRENCY) values (112,'kg','Kyrgyzstan',null);
Insert into country (ID,country_code,country_name,CURRENCY) values (113,'kh','Cambodia',null);
Insert into country (ID,country_code,country_name,CURRENCY) values (114,'ki','Kiribati',null);
Insert into country (ID,country_code,country_name,CURRENCY) values (115,'km','Comoros',null);
Insert into country (ID,country_code,country_name,CURRENCY) values (116,'kn','Saint Kitts and Nevis',null);
Insert into country (ID,country_code,country_name,CURRENCY) values (117,'kp','Korea, Democratic People''s Republic',null);
Insert into country (ID,country_code,country_name,CURRENCY) values (118,'kr','Korea, Republic of',null);
Insert into country (ID,country_code,country_name,CURRENCY) values (119,'kw','Kuwait',null);
Insert into country (ID,country_code,country_name,CURRENCY) values (120,'ky','Cayman Islands',null);
Insert into country (ID,country_code,country_name,CURRENCY) values (121,'kz','Kazakhstan',null);
Insert into country (ID,country_code,country_name,CURRENCY) values (122,'la','Lao, People''s Democratic Republic',null);
Insert into country (ID,country_code,country_name,CURRENCY) values (123,'lb','Lebanon',null);
Insert into country (ID,country_code,country_name,CURRENCY) values (124,'lc','Saint Lucia',null);
Insert into country (ID,country_code,country_name,CURRENCY) values (125,'li','Liechtenstein',null);
Insert into country (ID,country_code,country_name,CURRENCY) values (126,'lk','Sri Lanka',null);
Insert into country (ID,country_code,country_name,CURRENCY) values (127,'lr','Liberia',null);
Insert into country (ID,country_code,country_name,CURRENCY) values (128,'ls','Lesotho',null);
Insert into country (ID,country_code,country_name,CURRENCY) values (129,'lt','Lithuania',null);
Insert into country (ID,country_code,country_name,CURRENCY) values (130,'lu','Luxembourg',null);
Insert into country (ID,country_code,country_name,CURRENCY) values (131,'lv','Latvia',null);
Insert into country (ID,country_code,country_name,CURRENCY) values (132,'ly','Libyan Arab Jamahiriya',null);
Insert into country (ID,country_code,country_name,CURRENCY) values (133,'ma','Morocco',null);
Insert into country (ID,country_code,country_name,CURRENCY) values (134,'mc','Monaco',null);
Insert into country (ID,country_code,country_name,CURRENCY) values (135,'md','Moldova, Republic of',null);
Insert into country (ID,country_code,country_name,CURRENCY) values (136,'mg','Madagascar',null);
Insert into country (ID,country_code,country_name,CURRENCY) values (137,'mh','Marshall Islands',null);
Insert into country (ID,country_code,country_name,CURRENCY) values (138,'mk','Macedonia, Former Yugoslav Republic',null);
Insert into country (ID,country_code,country_name,CURRENCY) values (139,'ml','Mali',null);
Insert into country (ID,country_code,country_name,CURRENCY) values (140,'mm','Myanmar',null);
Insert into country (ID,country_code,country_name,CURRENCY) values (141,'mn','Mongolia',null);
Insert into country (ID,country_code,country_name,CURRENCY) values (142,'mo','Macau',null);
Insert into country (ID,country_code,country_name,CURRENCY) values (143,'mp','Northern Mariana Islands',null);
Insert into country (ID,country_code,country_name,CURRENCY) values (144,'mq','Martinique',null);
Insert into country (ID,country_code,country_name,CURRENCY) values (145,'mr','Mauritania',null);
Insert into country (ID,country_code,country_name,CURRENCY) values (146,'ms','Montserrat',null);
Insert into country (ID,country_code,country_name,CURRENCY) values (147,'mt','Malta',null);
Insert into country (ID,country_code,country_name,CURRENCY) values (148,'mu','Mauritius',null);
Insert into country (ID,country_code,country_name,CURRENCY) values (149,'mv','Maldives',null);
Insert into country (ID,country_code,country_name,CURRENCY) values (150,'mw','Malawi',null);
Insert into country (ID,country_code,country_name,CURRENCY) values (151,'mx','Mexico',null);
Insert into country (ID,country_code,country_name,CURRENCY) values (152,'my','Malaysia',null);
Insert into country (ID,country_code,country_name,CURRENCY) values (153,'mz','Mozambique',null);
Insert into country (ID,country_code,country_name,CURRENCY) values (154,'na','Namibia',null);
Insert into country (ID,country_code,country_name,CURRENCY) values (155,'nc','New Caledonia',null);
Insert into country (ID,country_code,country_name,CURRENCY) values (156,'ne','Niger',null);
Insert into country (ID,country_code,country_name,CURRENCY) values (157,'nf','Norfolk Island',null);
Insert into country (ID,country_code,country_name,CURRENCY) values (158,'ng','Nigeria',null);
Insert into country (ID,country_code,country_name,CURRENCY) values (159,'ni','Nicaragua',null);
Insert into country (ID,country_code,country_name,CURRENCY) values (160,'nl','Netherlands',null);
Insert into country (ID,country_code,country_name,CURRENCY) values (161,'no','Norway',null);
Insert into country (ID,country_code,country_name,CURRENCY) values (162,'np','Nepal',null);
Insert into country (ID,country_code,country_name,CURRENCY) values (163,'nr','Nauru',null);
Insert into country (ID,country_code,country_name,CURRENCY) values (164,'nu','Niue',null);
Insert into country (ID,country_code,country_name,CURRENCY) values (165,'nz','New Zealand',null);
Insert into country (ID,country_code,country_name,CURRENCY) values (166,'om','Oman',null);
Insert into country (ID,country_code,country_name,CURRENCY) values (167,'pa','Panama',null);
Insert into country (ID,country_code,country_name,CURRENCY) values (168,'pe','Peru',null);
Insert into country (ID,country_code,country_name,CURRENCY) values (169,'pf','French Polynesia',null);
Insert into country (ID,country_code,country_name,CURRENCY) values (170,'pg','Papua New Guinea',null);
Insert into country (ID,country_code,country_name,CURRENCY) values (171,'ph','Philippines',null);
Insert into country (ID,country_code,country_name,CURRENCY) values (172,'pk','Pakistan',null);
Insert into country (ID,country_code,country_name,CURRENCY) values (173,'pl','Poland',null);
Insert into country (ID,country_code,country_name,CURRENCY) values (174,'pm','St. Pierre and Miquelon',null);
Insert into country (ID,country_code,country_name,CURRENCY) values (175,'pn','Pitcairn Island',null);
Insert into country (ID,country_code,country_name,CURRENCY) values (176,'pr','Puerto Rico',null);
Insert into country (ID,country_code,country_name,CURRENCY) values (177,'pt','Portugal',null);
Insert into country (ID,country_code,country_name,CURRENCY) values (178,'pw','Palau',null);
Insert into country (ID,country_code,country_name,CURRENCY) values (179,'py','Paraguay',null);
Insert into country (ID,country_code,country_name,CURRENCY) values (180,'qa','Qatar',null);
Insert into country (ID,country_code,country_name,CURRENCY) values (181,'re','Reunion Island',null);
Insert into country (ID,country_code,country_name,CURRENCY) values (182,'ro','Romania',null);
Insert into country (ID,country_code,country_name,CURRENCY) values (183,'ru','Russian Federation',null);
Insert into country (ID,country_code,country_name,CURRENCY) values (184,'rw','Rwanda',null);
Insert into country (ID,country_code,country_name,CURRENCY) values (185,'sa','Saudi Arabia',null);
Insert into country (ID,country_code,country_name,CURRENCY) values (186,'sb','Solomon Islands',null);
Insert into country (ID,country_code,country_name,CURRENCY) values (187,'sc','Seychelles',null);
Insert into country (ID,country_code,country_name,CURRENCY) values (188,'sd','Sudan',null);
Insert into country (ID,country_code,country_name,CURRENCY) values (189,'se','Sweden',null);
Insert into country (ID,country_code,country_name,CURRENCY) values (190,'sg','Singapore',null);
Insert into country (ID,country_code,country_name,CURRENCY) values (191,'sh','St. Helena',null);
Insert into country (ID,country_code,country_name,CURRENCY) values (192,'si','Slovenia',null);
Insert into country (ID,country_code,country_name,CURRENCY) values (193,'sj','Svalbard and Jan Mayen Islands',null);
Insert into country (ID,country_code,country_name,CURRENCY) values (194,'sk','Slovak Republic',null);
Insert into country (ID,country_code,country_name,CURRENCY) values (195,'sl','Sierra Leone',null);
Insert into country (ID,country_code,country_name,CURRENCY) values (196,'sm','San Marino',null);
Insert into country (ID,country_code,country_name,CURRENCY) values (197,'sn','Senegal',null);
Insert into country (ID,country_code,country_name,CURRENCY) values (198,'so','Somalia',null);
Insert into country (ID,country_code,country_name,CURRENCY) values (199,'sr','Suriname',null);
Insert into country (ID,country_code,country_name,CURRENCY) values (200,'st','Sao Tome and Principe',null);
Insert into country (ID,country_code,country_name,CURRENCY) values (201,'sv','El Salvador',null);
Insert into country (ID,country_code,country_name,CURRENCY) values (202,'sy','Syrian Arab Republic',null);
Insert into country (ID,country_code,country_name,CURRENCY) values (203,'sz','Swaziland',null);
Insert into country (ID,country_code,country_name,CURRENCY) values (204,'tc','Turks and Ciacos Islands',null);
Insert into country (ID,country_code,country_name,CURRENCY) values (205,'td','Chad',null);
Insert into country (ID,country_code,country_name,CURRENCY) values (206,'tf','French Southern Territories',null);
Insert into country (ID,country_code,country_name,CURRENCY) values (207,'tg','Togo',null);
Insert into country (ID,country_code,country_name,CURRENCY) values (208,'th','Thailand',null);
Insert into country (ID,country_code,country_name,CURRENCY) values (209,'tj','Tajikistan',null);
Insert into country (ID,country_code,country_name,CURRENCY) values (210,'tk','Tokelau',null);
Insert into country (ID,country_code,country_name,CURRENCY) values (211,'tm','Turkmenistan',null);
Insert into country (ID,country_code,country_name,CURRENCY) values (212,'tn','Tunisia','TND');
Insert into country (ID,country_code,country_name,CURRENCY) values (213,'to','Tonga',null);
Insert into country (ID,country_code,country_name,CURRENCY) values (214,'tp','East Timor',null);
Insert into country (ID,country_code,country_name,CURRENCY) values (215,'tr','Turkey',null);
Insert into country (ID,country_code,country_name,CURRENCY) values (216,'tt','Trinidad and Tobago',null);
Insert into country (ID,country_code,country_name,CURRENCY) values (217,'tv','Tuvalu',null);
Insert into country (ID,country_code,country_name,CURRENCY) values (218,'tw','Taiwan',null);
Insert into country (ID,country_code,country_name,CURRENCY) values (219,'tz','Tanzania',null);
Insert into country (ID,country_code,country_name,CURRENCY) values (220,'ua','Ukraine',null);
Insert into country (ID,country_code,country_name,CURRENCY) values (221,'ug','Uganda',null);
Insert into country (ID,country_code,country_name,CURRENCY) values (222,'uk','United Kingdom',null);
Insert into country (ID,country_code,country_name,CURRENCY) values (223,'gb','United Kingdom',null);
Insert into country (ID,country_code,country_name,CURRENCY) values (224,'um','US Minor Outlying Islands',null);
Insert into country (ID,country_code,country_name,CURRENCY) values (225,'us','United States','USD');
Insert into country (ID,country_code,country_name,CURRENCY) values (226,'uy','Uruguay',null);
Insert into country (ID,country_code,country_name,CURRENCY) values (227,'uz','Uzbekistan',null);
Insert into country (ID,country_code,country_name,CURRENCY) values (228,'va','Holy See (City Vatican State)',null);
Insert into country (ID,country_code,country_name,CURRENCY) values (229,'vc','Saint Vincent and the Grenadines',null);
Insert into country (ID,country_code,country_name,CURRENCY) values (230,'ve','Venezuela',null);
Insert into country (ID,country_code,country_name,CURRENCY) values (231,'vg','Virgin Islands (British)',null);
Insert into country (ID,country_code,country_name,CURRENCY) values (232,'vi','Virgin Islands (USA)',null);
Insert into country (ID,country_code,country_name,CURRENCY) values (233,'vn','Vietnam',null);
Insert into country (ID,country_code,country_name,CURRENCY) values (234,'vu','Vanuatu',null);
Insert into country (ID,country_code,country_name,CURRENCY) values (235,'wf','Wallis and Futuna Islands',null);
Insert into country (ID,country_code,country_name,CURRENCY) values (236,'ws','Western Samoa',null);
Insert into country (ID,country_code,country_name,CURRENCY) values (237,'ye','Yemen',null);
Insert into country (ID,country_code,country_name,CURRENCY) values (238,'yt','Mayotte',null);
Insert into country (ID,country_code,country_name,CURRENCY) values (239,'yu','Yugoslavia',null);
Insert into country (ID,country_code,country_name,CURRENCY) values (240,'za','South Africa',null);
Insert into country (ID,country_code,country_name,CURRENCY) values (241,'zm','Zambia',null);
Insert into country (ID,country_code,country_name,CURRENCY) values (242,'zr','Zaire',null);
Insert into country (ID,country_code,country_name,CURRENCY) values (243,'zw','Zimbabwe',null);
Insert into country (ID,country_code,country_name,CURRENCY) values (250,'at','Austria',null);
Insert into country (ID,country_code,country_name,CURRENCY) values (251,'ps','Palestine',null);

